version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args: #Use this for linux
        USER_ID: $USER_ID #Use this for linux
        GROUP_ID: $GROUP_ID #Use this for linux
        USER_NAME: $USER_NAME #Use this for linux
    image: ayo-indonesia
    container_name: ayo-indonesia
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - ayo_indonesia
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ayo_indonesia
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ayo_indonesia
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ayo_indonesia

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8086:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - ayo_indonesia

networks:
  ayo_indonesia:

volumes:
  mysql_data:
